rdf_skos_language_mapping.settings:
  type: config_object
  label: 'Language mapping between the RDF SKOS and enabled languages of Drupal'
  mapping:
    language_mapping:
      type: sequence
      label: 'Language mapping configuration'
      sequence:
        type: string
        label: 'RDF SKOS langcode'
